name: PR Keyword and Version Correctness

on:
    pull_request:
        types: [opened, edited, synchronize]

jobs:
    validate-keywords:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get Versions
              id: versions
              run: |
                  # Get version from current PR branch
                  PR_VER=$(cat VERSION)
                  # Get version from the main branch
                  MAIN_VER=$(git show origin/main:VERSION)

                  echo "PR_VERSION=$PR_VER" >> $GITHUB_ENV
                  echo "MAIN_VERSION=$MAIN_VER" >> $GITHUB_ENV

            - name: Run keyword and version test script
              shell: node {0}
              env:
                  PR_BODY: ${{ github.event.pull_request.body }}
                  PR_VERSION: $ {{ env.PR_VERSION }}
                  MAIN_VERSION: $ {{ env.MAIN_VERSION }}
              run: |
                  require('./.github/scripts/check-keywords.js')
